#ifndef _QT_INC_FILES_ 
#define _QT_INC_FILES_
#include <QtCore/qnamespace.h>
#include <QtCore/qstring.h> 
#include <QtCore/QUrl> 
#include <QtCore/qfileinfo.h>
#include <QtCore/QCustomEvent>
#include <QtCore/qdatetime.h>
#include <QtCore/qtextstream.h>

#include <QtGui/qwidget.h> 
#include <QtGui/qlayout.h>
#include <QtGui/qvalidator.h>
#include <QtGui/qmenubar.h>
#include <QtGui/qmessagebox.h>
#include <QtGui/qlabel.h>
#include <QtGui/qapplication.h>
#include <QtGui/qradiobutton.h>
#include <QtGui/qcursor.h>
#include <QtGui/qfiledialog.h>
#include <QtGui/qcombobox.h>
#include <QtGui/qtooltip.h>
#include <QtGui/qtoolbar.h>
#include <QtGui/qtoolbutton.h>
#include <QtGui/qstatusbar.h> 
#include <QtGui/qstyle.h> 
#include <QtGui/qpushbutton.h> 
#include <QtGui/qprogressbar.h>
#include <QtGui/QProgressDialog>
#include <QtGui/qevent.h>
#include <QtGui/qfiledialog.h>
#include <QtGui/qdesktopservices.h>
#include <QtGui/qtextedit.h>
#include <QtGui/qprinter.h>
#include <QtGui/qprintdialog.h>
#include <QtGui/qdockwidget.h>
#include <QtGui/qlistwidget.h>
#include <QtGui/qsplitter.h>
#include <QtGui/qscrollarea.h>
#include <QtCore/qtimer.h>

#endif //_QT_INC_FILES_